package net.filebot.backend.service;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import net.filebot.backend.domain.ChecksumStatus;
import net.filebot.backend.domain.HashType;
import net.filebot.backend.dto.ChecksumEntryDto;
import net.filebot.backend.dto.ChecksumExportRequestDto;
import net.filebot.backend.dto.ChecksumVerificationRequestDto;
import net.filebot.hash.SfvFormat;
import net.filebot.hash.VerificationFileReader;
import org.springframework.stereotype.Service;

@Service
public class ChecksumServiceImpl implements ChecksumService {

  @Override
  public String startVerificationTask(ChecksumVerificationRequestDto request) {
    if (request == null) {
      return "";
    }
    return UUID.randomUUID().toString();
  }

  @Override
  public void cancelVerificationTask(String taskId) {
    // No-op for task cancellation
  }

  @Override
  public List<ChecksumEntryDto> parseVerificationFile(String sfvFilePath) {
    if (sfvFilePath == null || sfvFilePath.isBlank()) {
      return Collections.emptyList();
    }

    File file = new File(sfvFilePath);
    if (!file.exists()) {
      return Collections.emptyList();
    }

    List<ChecksumEntryDto> dtos = new ArrayList<>();
    try (FileReader reader = new FileReader(file, StandardCharsets.UTF_8);
        VerificationFileReader verificationReader =
            new VerificationFileReader(reader, new SfvFormat())) {
      while (verificationReader.hasNext()) {
        Map.Entry<File, String> entry = verificationReader.next();
        dtos.add(
            new ChecksumEntryDto(
                entry.getKey().getPath(),
                entry.getValue(),
                null,
                HashType.CRC32,
                ChecksumStatus.COMPUTING));
      }
    } catch (Exception e) {
      return Collections.emptyList();
    }
    return dtos;
  }

  @Override
  public String generateVerificationFileContent(ChecksumExportRequestDto request) {
    if (request == null || request.entries() == null) {
      return "";
    }

    StringBuilder sb = new StringBuilder("; Generated by FileBot\n");
    for (ChecksumEntryDto entry : request.entries()) {
      String hash = entry.calculatedHash() != null ? entry.calculatedHash() : entry.expectedHash();
      if (hash != null) {
        sb.append(entry.path()).append(" ").append(hash).append("\n");
      }
    }

    if (request.outputPath() != null && !request.outputPath().isBlank()) {
      try (FileWriter writer = new FileWriter(request.outputPath(), StandardCharsets.UTF_8)) {
        writer.write(sb.toString());
      } catch (Exception e) {
        // Ignore file write exception
      }
    }

    return sb.toString();
  }
}
